### PR TITLE
Feature/theForest 🌲🌲

### PR DESCRIPTION
**Pull request by Major-Eth**
## What it does ✨
Add The Forest V2 to Rarity Extended. This is a big PR with a lot of changes on the new Dungeon but also on some elements of the UI/UX.
Changes :
- Adding integration with `The Forest V2` to be able to get the Artefacts for one address
- Adding integration with `The Forest V2` to be able to levelup the Artefacts agains some XP
- Adding integration with `The Forest V2` to be able to start a research for 4 to 7 days
- Adding integration with `The Forest V2` to be able to discover an Artefact after 4 to 7 days
- Adding integration with `The Forest V2` to be able to Restore items from `The Forest V1` (aka migration)
- Updating the inventory to be able to display the level/rarity of an item (common, uncommon, rare, epic, legendary, relic)
- Updating the inventory to be able to display details on hover
- Updating the way the items are fetched
- Adding some stuff for the BlackSmith
- Adding visual, descriptions and details for each items 

## How to test ✅
You should be able to go in the Forest, Dig, upgrade the level of your treasure without issue

## Note 📝
- A way to know that your adventurer are back from The Forest could be great

## Visuals 🌄
Capture d’écran 2021-09-19 à 16 59 44
Capture d’écran 2021-09-19 à 17 03 55
Capture d’écran 2021-09-19 à 17 08 00
Capture d’écran 2021-09-19 à 16 32 56
Capture d’écran 2021-09-18 à 18 24 34

### CODE REVIEW

**Review by TheAustrian1998 — COMMENTED** [review]
Good job Major!. I was able to test all functions (research, discover, level up) except restore an artifact. I was receiving this error in the blacksmith: 
Screenshot-20210919145726-964x733
Maybe is a problem with my local installation.

**Review by TheAustrian1998 — APPROVED** [review]
All working as expected!

**Comment by DarkGhost7** [comment]
Let's goo! Can't wait to play the forest. Keep up the good work guys!!

**Comment by saltyfacu** [comment]
- All the quests should only be in the Quest Office. Go to the Tavern should be removed.
Screenshot 2021-09-20 at 15 49 28

- Is "About the rat" the same as "The Cellar"? If so, we should remove the rat from the Tavern.
Screenshot 2021-09-20 at 15 50 29

- When I go to the quest office and go to the cellar, I fight the rat, and when I pass out, I go back to the tavern. I think we should go to the Quest Office.

- When I send my adventurer to the Forest, on the "Adventurers" page I still see the adventurer like the image below. I think this text has to be in a second place, using the arrows we usually use, so you can see that you've already sent your people to the forest, and the days left there. If your guy is in the forest... you can also send him to another adventure at the same time? 🤷‍♂️

Screenshot 2021-09-20 at 15 53 25

**Comment by Major-Eth** [comment]
@saltyfacu as discussed: 
- I removed the `Go to the Tavern` button in the inventory
- Redirect to the Quest office instead of the Tavern for the rat

**Review by saltyfacu — APPROVED** [review]
lgtm

**Comment by saltyfacu** [comment]
When claiming XP, the notification says "Going to an adventure"

Screenshot 2021-09-20 at 17 34 20

**Comment by saltyfacu** [comment]
Looks good to me :) Merge at will

**Pull request merged**
